version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
#   commands:
#      - echo Installing Nodejs 0.10.48 ...
#      - curl -fsSL https://deb.nodesource.com/setup_10.x | bash -
 #     - apt-get install -y nodejs
 #     - curl -sL https://deb.nodesource.com/setup_0.10 | bash -
 #     - apt-cache policy nodejs
 #     - sudo apt-get install -y nodejs=0.10.48-*
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build...
      - npm run-script build
artifacts:
  files:
    - "**/*"
  giscard-paths: no
#  base-directory: dist
