version: '3'

services:
#   DATABASE
  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mykola
      MONGO_INITDB_ROOT_PASSWORD: mykpas
    ports:
      - "27017:27017"
    networks:
      - my-network
#   BACKEND
  chess-back:
    image: mykolacompany/chess-back
    environment:
      DB_URL: "mongodb://mykola:mykpas@mongodb:27017/chessMEAN?authSource=admin"
    ports:
      - "8081:8081"
    links:
      - mongodb
    networks:
      - my-network
#   FRONTEND
  chess-front:
    image: mykolacompany/chess-front
    environment:
      API_URL: "http://localhost:8081"
    ports:
      - "8080:80"
    depends_on:
      - chess-back
    networks:
      - my-network

networks:
  my-network:
    driver: bridge