
# FILE: Dockerfile

### STAGE 1: Build ###

# We label our stage as 'builder'
FROM node:10-alpine as builder

#ARG API_URL
#ENV API_URL "API_URL"

RUN mkdir /nodejs-app
COPY . /nodejs-app
WORKDIR /nodejs-app

RUN npm install
#--ignore-scripts --no-optional
RUN npm run build


### STAGE 2: Setup ###
FROM nginx:1.13.3-alpine

## Remove default nginx website
RUN rm -rf /usr/share/nginx/html/*

## From 'builder' stage copy over the artifacts in dist folder to default nginx public folder
COPY --from=builder /nodejs-app/lib/client /usr/share/nginx/html

COPY --from=builder /nodejs-app/scripts/replace_api_url.sh /

CMD ["sh", "replace_api_url.sh"]

#CMD ["nginx", "-g", "daemon off;"]